---
- hosts: all
  roles:

  # osx config
  - role: dock
    apps:
    - /Applications/Firefox.app
    - /Applications/Spotify.app
    - /Applications/Atom.app
    - /Applications/iTerm.app
    folders:
    - path: ~/
    - path: ~/Documents
    - path: ~/Downloads
      sort: datemodified
  - role: cask_package
    package_name: asepsis
  - role: dashboard
    disabled: YES

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-source-code-pro
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-sauce-code-powerline

  # cli
  # shell tooling
  - role: git
    git_user_name: Krishnaswamy Subramanian 
    git_user_email: subramk@thoughtworks.com
  - role: legit
  - role: hub
  - role: brew_package
    package_name: vim
  ## languages
  - role: brew_package
    package_name: node
  - role: rbenv
  - role: cask_package
    package_name: java
  ## databases
  ## deployment
  # - role: brew_package
  #   package_name: ansible # Hey ! Already there !

  # gui
  ## text editors
  - role: cask_package
    package_name: atom
