---
- hosts: all
  roles:

  # osx config
  - role: dock
    folders:
    - path: ~/
    - path: ~/Documents
    - path: ~/Downloads
      sort: datemodified
  - role: cask_package
    package_name: asepsis
  - role: dashboard
    disabled: YES

  # cli
  # shell tooling
  - role: git
    git_user_name: Krishnaswamy Subramanian 
    git_user_email: subramk@thoughtworks.com
  - role: legit
  - role: hub
  - role: brew_package
    package_name: vim
  ## languages
  - role: brew_package
    package_name: node
  - role: rbenv
  - role: cask_package
    package_name: java
  ## databases
  ## deployment
  # - role: brew_package
  #   package_name: ansible # Hey ! Already there !

  # gui
  ## text editors
  - role: cask_package
    package_name: atom

  # go-client 
  - role: cask_package
    package_name: go-agent

  # cocoapods
  - role: gem_package
    package_name: cocoapods

  # xctool
  - role: brew_package
    package_name: xctool 
